name: "1st of Month: Issues & PRs"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      CI_COMMIT_MESSAGE: CI EOM Issues and PRs
      CI_COMMIT_AUTHOR: CI with PAT

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Get date
      id: date
      run: echo "::set-output name=date::$(date +'%y%m%d')"

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create new branch
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git checkout -b first-of-month-issues-and-prs
        git push --set-upstream origin first-of-month-issues-and-prs
        
    - name: Install and run 
      run: |
        cd automation/first-of-month
        npm ci
        node index.js > ../../github/stats/${{ steps.date.outputs.date }}_issues_and_prs.md
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "$(date +'%B %Y') issues and PRs"

    # Commit and push all changed files. 
    # Must only affect files that are listed in "paths-ignore".
    # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html#example-1
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      run: |
        git push