name: "Manual: GitHub time"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Display GitHub time
      run: |
          echo "GitHub time: $(date --utc --iso-8601=seconds)"
      shell: bash
