name: "Daily: My History"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  DRAFT_FILE: assigned_issues_output
  REPORT_NAME: daily_issues_and_prs
  REPORT_EXTENSION: json

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      CI_COMMIT_MESSAGE: CI EOM Issues and PRs
      CI_COMMIT_AUTHOR: CI dfberry pat

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}


    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Issues and PRs for me
      run: |
        cd automation/my-history
        npm ci
        ls -al
        node --loader ts-node/esm src/index.ts > data/${{ env.DRAFT_FILE }}.${{ env.REPORT_EXTENSION}}
        ls -al data
        cat data/${{ env.DRAFT_FILE }}.${{ env.REPORT_EXTENSION}}
        cp data/${{ env.DRAFT_FILE }}.${{ env.REPORT_EXTENSION}} ../../github/stats/${{ steps.date_yesterday.outputs.date }}_${{ env.REPORT_NAME }}.${{ env.REPORT_EXTENSION}}
        ls -al ../../github/stats

    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "dfberry@users.noreply.github.com"
        git add github/stats/${{ steps.date_yesterday.outputs.date }}_${{ env.REPORT_NAME }}.${{ env.REPORT_EXTENSION}}
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        branch: main
